### ISSUE TITLE
[LANDING] recherche interaction ancre

### ISSUE THREAD

**Issue by nute-25** [nute-25/the_octopus#11]
Rechercher quelle animation js permet de passer par un système d'ancre d'un bloc à un autre.

**Comment by YoniWoo** [comment]
Pour faire le scroll au coup de molette on peut utiliser l'event onwheel. Le but serait de passer d'une ancre à l'autre avec l'evenement. 

[DOC Event onwheel](https://developer.mozilla.org/fr/docs/Web/API/Element/onwheel)
